#!/bin/bash

echo "STARTING DEPLOYMENT"

HEROKU_APP_NAME=${1:?'You need to provide the application name as a parameter on the command line.'}
: ${HEROKU_API_KEY?"Set the HEROKU_API_KEY environment variable. Get the key from https\:\/\/dashboard.heroku.com\/account"}

function error_message() {
  echo -e "Deployment Failed"
}
trap error_message ERR

set -o pipefail
set -e

echo "CHECKING Access to Heroku application $HEROKU_APP_NAME"
check_access_to_heroku_app $HEROKU_APP_NAME

ARTEFACT_PATH=/tmp/deployable_artifact.tar.gz

echo "PACKAGING tar.gz for deployment"
tar -pczf $ARTEFACT_PATH ./

echo "PREPARING Heroku source for upload"
sources=`curl -sS -X POST https://api.heroku.com/apps/$HEROKU_APP_NAME/sources -H 'Accept: application/vnd.heroku+json; version=3' -H "Authorization: Bearer $HEROKU_API_KEY"`

get_url=`echo $sources | jq -r .source_blob.get_url`
put_url=`echo $sources | jq -r .source_blob.put_url`

echo "UPLOADING tar.gz file to Heroku"
curl -sS -X PUT "$put_url" -H 'Content-Type:' --data-binary @$ARTEFACT_PATH

echo "STARTING Build process on Heroku"
deployment=`curl -sS -X POST https://api.heroku.com/apps/codeship-heroku-deployment/builds -d "{\"source_blob\":{\"url\":\"$get_url\", \"version\": \"sfghdjhtjtjdghjdhdfghdfghfdshsggadfg\"}}" -H 'Accept: application/vnd.heroku+json; version=3' -H 'Content-Type: application/json' -H "Authorization: Bearer $HEROKU_API_KEY"`

deployment_id=`echo "$deployment" | jq -r .id`

output_stream_url=`echo "$deployment" | jq -r .output_stream_url`

curl -sS "$output_stream_url"

curl -sS https://api.heroku.com/apps/$HEROKU_APP_NAME/builds/$deployment_id -H 'Accept: application/vnd.heroku+json; version=3' -H "Authorization: Bearer $HEROKU_API_KEY" | jq .status | grep "succeeded" > /dev/null

echo "SUCCESSFULL DEPLOYMENT"
